# Generated by Django 4.2.1 on 2023-05-22 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionary_app', '0002_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('phrase', models.CharField(max_length=500)),
                ('translate', models.CharField(max_length=500)),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='A1', max_length=10)),
                ('published', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phrases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
