# Generated by Django 4.2.1 on 2023-05-23 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_app', '0003_word_published_phrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='phrase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phrase_chellenges', to='dictionary_app.phrase'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word_chellenges', to='dictionary_app.word'),
        ),
    ]
