# Generated by Django 4.2.1 on 2023-05-19 21:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0002_subnow'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporalyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('value', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='subnow',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='subnow',
            name='promo_code',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subnow',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
