# Generated by Django 4.2.1 on 2023-05-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0003_temporalytoken_subnow_price_subnow_promo_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='max_words',
            field=models.IntegerField(default=3),
        ),
    ]
