# Generated by Django 4.2.1 on 2023-05-21 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0004_subscription_description_subscription_max_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='max_words',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='period',
            field=models.CharField(choices=[('month', 'Month')], default='month', max_length=10),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField(default=0.0)),
                ('currency', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('paytype', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('order_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('liqpay_order_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('payment_id', models.IntegerField(default=0)),
                ('ip', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
