# Generated by Django 4.2.1 on 2023-05-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0006_alter_transaction_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='max_phrases',
            field=models.IntegerField(default=5),
        ),
    ]
