# Generated by Django 4.2.1 on 2023-06-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0007_subscription_max_phrases'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('source', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('value', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
